### ISSUE TITLE
Add a license

### ISSUE THREAD

**Issue by s-burris** [lorenz/zfs_exporter#1]
Hello,
I'm interested in using and potentially contributing to this software. However, I'm currently uncomfortable with doing so due to the lack of license. Would you be willing to add one?

**Comment by lorenz** [comment]
I [licensed](https://github.com/lorenz/zfs_exporter/commit/cd8d1abe2d5aafac23362929527e683b2f5a40de) it under Apache 2, same as most other Prometheus-related projects.

**Comment by s-burris** [comment]
Awesome, thank you.
